services:
  - type: web
    name: ecommerce-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: RENDER
        value: True
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
    disk:
      name: static-files
      mountPath: /app/staticfiles
      sizeGB: 1

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce