services:
  - type: web
    name: ecommerce-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: RENDER
        value: True
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_heU84ctdoNSq@ep-twilight-dream-ad1kc99m-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
    disk:
      name: static-files
      mountPath: /app/staticfiles
      sizeGB: 1

# Using external Neon database instead of Render-managed database
# databases:
#   - name: ecommerce-db
#     databaseName: ecommerce
#     user: ecommerce